import {Work_Sans} from 'next/font/google'
import { Advent_Pro } from 'next/font/google'

const work = Work_Sans ({
  subsets: ['latin'],
  display:'swap'
})


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en" className={work.className}>
      <body>{children}</body>
    </html>
  )
}
